services:
  xboard-node:
    image: ghcr.io/neukchill/xboard-node:latest
    container_name: xboard-node
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config:/etc/xboard-node
      - ./cert.pem:/etc/xboard-node/cert.pem
      - ./key.pem:/etc/xboard-node/key.pem
    command: ["-c", "/etc/xboard-node/config.yml"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
